[package]
name = "pips-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
lazy_static = "1.5.0"
nom = "8.0.0"
rayon = "1.11.0"
regex = "1.12.2"
